resources/assets/js/components/SideBar/index.js
resources/assets/js/components/SideBar/routes.js

https://github.com/JiaAnTW/NCKU_Trans/issues/62
Refactoring the code in `SideBar/index.js`
- Move `routers` in `SideBar/index.js` to `SideBar/routes.js`
- Move `adminRouters` in `SideBar/index.js` to `SideBar/routes.js`

refactor: move routers from SideBar in routes.js

---

resources/assets/js/page/Major/Statistic/style.js
resources/assets/js/page/Major/index.js
resources/assets/js/page/Major/style.js
resources/assets/js/theme/global.js

修改cardList捲動方式
https://github.com/JiaAnTW/NCKU_Trans/issues/67
- /

Fix: Scrolling Scope of Major Page

---

resources/assets/js/components/NavLayout/Banner/index.js
resources/assets/js/components/NavLayout/Banner/style.js
resources/assets/js/components/NavLayout/Title/style.js
resources/assets/js/components/NavLayout/index.js
resources/assets/js/components/NavLayout/style.js

- remove sidebar menu icon for pc
- reposition header for mobile
#65

feat: remove sidebar menu icon for pc

---

resources/assets/js/components/LoagingFrame/index.js
resources/assets/js/page/Department/index.js
resources/assets/js/page/Major/index.js
resources/assets/js/page/Post/index.js

feat: separate loading frame

---

resources/assets/js/components/atom/Badge/index.js
resources/assets/js/components/atom/Badge/style.js
resources/assets/js/theme/global.js

- Add a new atom component, Badge
- Can be with or without close button
- /

feat: Add new component - badge

---

resources/assets/js/components/TransCard/useOpenContent.js
resources/assets/js/page/Major/CardList/useCommentFlow.js
resources/assets/js/utils/seo/useCloseReader.js

Node.js without --experimental-json-modules flag will emit error when importing json file.

fix: add extension when importing json file

---

app/Http/Controllers/CommentsController.php

讓取得轉輔雙主心得API回傳由新到舊的資料
https://github.com/JiaAnTW/NCKU_Trans/issues/83
- /major

feat: reverse major by id in BE side

---

app/Http/Controllers/StudyController.php
routes/api.php

For more detail information of api, please take a look in
JiaAnTW/NCKU_Trans repo wiki.

feat: add /api/get/study and it response fake data

---

resources/assets/js/components/SearchBar/index.js
resources/assets/js/components/SearchBar/style.js

Implement search-bar component, submit on clicking button or pressing enter only.
#45

feat: implement SearchBar component

---

resources/assets/js/components/StudyReader/AdminAdvance/index.js
resources/assets/js/components/StudyReader/AdminAdvance/style.js
resources/assets/js/components/StudyReader/ChangeBtn/index.js
resources/assets/js/components/StudyReader/ChangeBtn/style.js
resources/assets/js/components/StudyReader/Confirm/index.js
resources/assets/js/components/StudyReader/Confirm/style.js
resources/assets/js/components/StudyReader/StatisticBlock/StatisticItem/index.js
resources/assets/js/components/StudyReader/StatisticBlock/StatisticItem/style.js
resources/assets/js/components/StudyReader/StatisticBlock/index.js
resources/assets/js/components/StudyReader/StatisticBlock/style.js
resources/assets/js/components/StudyReader/Title/index.js
resources/assets/js/components/StudyReader/Title/style.js
resources/assets/js/components/StudyReader/index.js
resources/assets/js/components/StudyReader/style.css
resources/assets/js/components/StudyReader/style.js
resources/assets/js/components/atom/Button/index.js
resources/assets/js/model/action/study.js
resources/assets/js/model/middleware/study.js
resources/assets/js/page/Post/index.js
resources/assets/js/theme/global.js

- Implement reader of study page.
- Fix misspelling prop of Button.
- Reserve space for statistic, filter components. (filter is implemented, but coupling with study page)
- Redirect for editing is **not** done, waiting for https://github.com/JiaAnTW/NCKU_Trans/issues/46 done.
#44 
- component
- atom/Button
- color

feat: implement StudyReader

---

app/Http/Controllers/StudyController.php
app/study.php
database/migrations/2022_01_20_145757_create_study_table.php
routes/api.php

- Added Study API : create, update, patch, and delete.
- In this PR, the data of category and statistic are still fake.
- #78 
- /
- /post
- /admin/*
- component
- SideBar

feat: add schema and API for study

---

app/Http/Controllers/StatisticManageController.php
app/Http/Controllers/StudyController.php
app/StatisticManage.php
database/migrations/2022_01_20_154537_create__statistic_manage_table.php
routes/api.php

Added API : show, create, update, and delete.
In this commit, when detected some error and return fail, some
data had already create. Before returning fail, it won't  delete
from database. Causing those data can't be access, needed to delete
them manually.
- #78

feat:add schema and API for statistic

---

database/seeds/CategoryManageTableSeeder.php
database/seeds/DatabaseSeeder.php
database/seeds/StatisticManageTableSeeder.php
database/seeds/StudyTableSeeder.php

With command, laravel will insert fake data automatically.
- #120

feat:insert fake data with command

---

app/Http/Controllers/StudyController.php
routes/api.php

- add get all confirmed study api
- get all study api need to be authenticated
- #78

feat:add get all confirmed study api

---

app/Http/Controllers/CategoryManageController.php
app/Http/Controllers/StatisticManageController.php
app/Http/Controllers/StudyController.php

- return uuid for create api of studyStat and studyType
- fix error that will return null value in statistics of get study api

return uuid after create success and fix error

---

app/Http/Controllers/CategoryManageController.php
app/Http/Controllers/StatisticManageController.php
routes/api.php

- Adjust studyType post format
- fix without checking dataType of studyStat
- incorrect url name of studyStat update api

Adjust studyType post format and fix without checking dataType of studyStat

---

resources/assets/js/_tests_/model/reducer/post.test.js
resources/assets/js/_tests_/model/reducer/post/initStudy.js
resources/assets/js/_tests_/utils/redux/component/modal/transFormData.test.js
resources/assets/js/components/SearchBar/InputBar.js
resources/assets/js/components/SearchBar/index.js
resources/assets/js/components/SearchBar/style.js
resources/assets/js/components/atom/Label/style.js
resources/assets/js/components/atom/PreviewInput/index.js
resources/assets/js/components/atom/PreviewInput/style.js
resources/assets/js/components/atom/ToggleButtonGroup/index.js
resources/assets/js/model/reducer/post/function/index.js
resources/assets/js/model/reducer/post/function/searchingAlgo.js
resources/assets/js/model/reducer/post/index.js
resources/assets/js/model/reducer/post/initStudy.js
resources/assets/js/model/reducer/post/mapToCustomFunction.js
resources/assets/js/page/Post/PostForm/InputList/PostInput/index.js
resources/assets/js/page/Post/PostForm/usePostControl.js
resources/assets/js/page/Post/PostForm/useSubmit.js
resources/assets/js/utils/redux/components/modal/dataMapping.js

- encapsulate some function to dataMapping
- able Searching (match prob:<50)
- some new feat ~ let see in Files changed or Commit Msg XD (so sorry about that)
https://github.com/JiaAnTW/NCKU_Trans/issues/119
- /
- /post
- /admin/*
- component
- SideBar

feat: add_default_input

---

app/Http/Controllers/StatisticManageController.php

- fix studyStat update api do not return status
- When updating studyStat without changing the name, it will return fail

fix studyStat api error

---

app/Http/Controllers/StudyController.php
database/migrations/2022_01_20_145757_create_study_table.php
database/seeds/CategoryManageTableSeeder.php
database/seeds/StudyTableSeeder.php

- category seeder didn't change data key from studyType to name
- add field for study for recording applying year

fix category seeder error and add field for study

---

resources/assets/js/model/reducer/post/index.js

- input button and type lost
On Pending
https://github.com/JiaAnTW/NCKU_Trans/pull/140
- /
- /post
- /admin/*
- component
- SideBar

fix: input button and type lost

---

resources/assets/js/components/StudyCard/index.js
resources/assets/js/components/StudyReader/AdminAdvance/index.js
resources/assets/js/components/StudyReader/CategoryBlock/index.js
resources/assets/js/components/StudyReader/StatisticBlock/index.js
resources/assets/js/model/middleware/study.js
resources/assets/js/model/reducer/study.js
resources/assets/js/page/Study/CardList/index.js
resources/assets/js/page/Study/CardList/useFetchData.js
resources/assets/js/page/Study/index.js
resources/assets/js/page/Study/style.js
resources/assets/js/page/Study/useInitData.js
resources/assets/js/utils/redux/components/modal/transIntoModalData.js

- batch update
- connect confirm / delete api
#103

feat: batch update for study

---

resources/assets/js/model/selector/study.js
resources/assets/js/page/Study/StatAnalysis/Column/dataColumn.js
resources/assets/js/page/Study/StatAnalysis/Column/style.js
resources/assets/js/page/Study/StatAnalysis/Column/typeNameColumn.js
resources/assets/js/page/Study/StatAnalysis/index.js
resources/assets/js/page/Study/StatAnalysis/style.js
resources/assets/js/page/Study/index.js
resources/assets/js/page/Study/style.js

- Desktop version for displaying stat data
- Stat type is from Redux store, can show selected stat filter
- Hardcoded 2 rows of number data 
- https://github.com/JiaAnTW/NCKU_Trans/issues/48
- /

Feat/stat UI

---

app/Http/Controllers/OtherStatisticController.php
app/Http/Controllers/StudyController.php
app/OtherStatistic.php
app/Study.php
database/migrations/2022_03_05_022734_create_other_statistic_table.php
database/seeds/StudyTableSeeder.php
routes/api.php

- create otherStat for storing uncreated studyStat
- API:
- /api/get/otherStat show all otherStat
- /api/post/transformStudyStat transform one otherStat entry into one existing studyStat
- #134

feat:add otherStat for storing uncreated studyStat

---

app/Category.php
app/CategoryManage.php
app/Http/Controllers/CategoryManageController.php
app/Http/Controllers/StudyController.php
database/migrations/2022_01_20_154718_create__category_table.php
database/seeds/StudyTableSeeder.php

- fix relation problem when updating / deleting categories
- remove redundant data in seeder
#44 
#78 
#149

feat: adjust relationship between category and management

---

app/Http/Controllers/StudyController.php
resources/assets/js/model/reducer/study.js

- fix inappropriate syntax in admin-study
- refresh tag name when updating successfully
#44 #78
#148 #149

fix: inappropriate syntax in admin-study

---

app/Http/Controllers/StudyController.php

在通用心得支援搜尋字串功能(因為第二階段比較好做，先做第二階段)
- ex: http://127.0.0.1:8000/api/get/study?num=30&p=test
- ex: http://127.0.0.1:8000/api/get/study?num=30&p=實習
- https://github.com/JiaAnTW/NCKU_Trans/issues/128

feat: support get study with query terms

---

resources/assets/js/components/atom/PairInput/index.js
resources/assets/js/model/reducer/post/initStudy.js
resources/assets/js/page/Post/PostForm/postDataList.js
resources/assets/js/page/Post/PostForm/useSubmitTransData.js

- fix: create post structure of sending to backend adjust
https://github.com/JiaAnTW/NCKU_Trans/issues/157
- /
- /post
- /admin/*
- component
- SideBar

fix: create post structure of sending to backend adjust

---

resources/assets/js/components/NavLayout/Banner/index.js
resources/assets/js/components/NavLayout/Title/index.js
resources/assets/js/components/NavLayout/Title/style.js
resources/assets/js/components/NavLayout/index.js
resources/assets/js/components/NavLayout/style.js
resources/assets/js/page/Study/Search/index.js
resources/assets/js/page/Study/Search/style.js
resources/assets/js/page/Study/index.js

- feat: add search bar in study page
https://github.com/JiaAnTW/NCKU_Trans/issues/133
- /
- /post
- /admin/*
- component
- SideBar

feat: study filter search bar

---

app/Http/Controllers/StudyController.php

讓get study的API支援統計項目和類別的篩選
ex: http://127.0.0.1:8000/api/get/study?num=30&categoryFilter=fe39b471-7cf3-4e99-a4e7-7948357df2dd&statFilter=65061e3f-1056-4c28-b0f3-757e7161f252
- https://github.com/JiaAnTW/NCKU_Trans/issues/128
- https://github.com/JiaAnTW/NCKU_Trans/pull/152

feat: support get study with query filter

---

resources/assets/js/app.js
resources/assets/js/components/NavLayout/NavSearchProvider.js
resources/assets/js/components/NavLayout/Title/index.js
resources/assets/js/components/SearchBar/index.js
resources/assets/js/model/middleware/study.js
resources/assets/js/page/Study/useInitData.js

- https://github.com/JiaAnTW/NCKU_Trans/issues/154

feat: connect search api

---

app/Http/Controllers/CommentsController.php
app/Http/Controllers/StudyController.php
resources/assets/js/components/StudyCard/useOpenContent.js
resources/assets/js/model/selector/study.js
resources/assets/js/page/Study/CardList/useCommentFlow.js
resources/assets/js/wording/general.json
resources/lang/zh_tw/comment.php
resources/lang/zh_tw/study.php
routes/web.php

- 在backend以SSR處理要給爬蟲看得SEO的內容
- 在frontend同步切換文章時的title和header
- https://github.com/JiaAnTW/NCKU_Trans/issues/60

feat: support seo for study

---

resources/assets/js/page/Study/CardList/useFetchData.js

fix: duplicated items when # of listed items are equal to 2

---

resources/assets/js/components/Statisitc/StatisticItem/index.js
resources/assets/js/components/Statisitc/StatisticItem/style.js
resources/assets/js/components/Statisitc/index.js
resources/assets/js/components/Statisitc/style.js
resources/assets/js/page/Study/CardList/style.js
resources/assets/js/page/Study/Filter/style.js
resources/assets/js/page/Study/index.js
resources/assets/js/page/Study/style.js

feat: add statistic block

---

resources/assets/js/components/Statisitc/index.js
resources/assets/js/components/StatisticControl/index.js
resources/assets/js/components/StatisticControl/style.js
resources/assets/js/page/Major/EssayFilter/style.js
resources/assets/js/page/Major/Statistic/index.js
resources/assets/js/page/Major/index.js
resources/assets/js/page/Major/style.js

讓轉輔心得的統計資料在手機和平板上以float btn顯示
- https://github.com/JiaAnTW/NCKU_Trans/issues/48
- /
- /post
- /admin/*
- component
- SideBar

feat: add stat btn on mobile

---

resources/assets/js/components/Form/StepArea/index.js
resources/assets/js/components/Form/StepArea/style.js
resources/assets/js/model/reducer/post/initComment.js
resources/assets/js/model/reducer/post/initStudy.js
resources/assets/js/model/selector/post.js

更新表單進度條的造型
- https://github.com/JiaAnTW/NCKU_Trans/issues/32
- /
- /post
- /admin/*
- component
- SideBar

feat: update step style

---

resources/assets/js/model/middleware/study.js

fix: updateStudy not matched API data
https://github.com/JiaAnTW/NCKU_Trans/issues/175
- /
- /post
- /admin/*
- component
- SideBar

fix: updateStudy not matched API data

---

database/seeds/CategoryManageTableSeeder.php
database/seeds/StatisticManageTableSeeder.php
database/seeds/StudyTableSeeder.php

建立真正要用的學業心得seeder
- https://github.com/JiaAnTW/NCKU_Trans/issues/120
- /
- /post
- /admin/*
- component
- SideBar

feat: update seeder

---

resources/assets/js/model/middleware/study.js
resources/assets/js/model/reducer/study.js
resources/assets/js/page/Study/CardList/useFetchData.js

- https://github.com/JiaAnTW/NCKU_Trans/issues/176
- /
- /post
- /admin/*
- component
- SideBar

fix: stop fetching study data when it reach end

---

resources/assets/js/components/Reader/AdvanceAdmin/EditBtn.js
resources/assets/js/components/StudyReader/AdminAdvance/index.js
resources/assets/js/model/reducer/post/index.js

- study overwrite post form doesn't work
https://github.com/JiaAnTW/NCKU_Trans/issues/188
https://github.com/JiaAnTW/NCKU_Trans/commit/c18898d79e43f0f25995496dae11f9e467c2afde
- /
- /post
- /admin/*
- component
- SideBar

fix: study overwrite post form doesn't work

---

resources/assets/js/utils/redux/components/modal/dataMapping.js

- couldn't fetch otherStat key into preview modal
https://github.com/JiaAnTW/NCKU_Trans/issues/157
https://github.com/JiaAnTW/NCKU_Trans/pull/156
- /
- /post
- /admin/*
- component
- SideBar

fix: couldn't fetch otherStat key into preview modal

---

resources/assets/js/_tests_/model/reducer/post/initStudy.js
resources/assets/js/model/reducer/post/index.js
resources/assets/js/model/reducer/post/initStudy.js
resources/assets/js/model/reducer/post/mapToCustomFunction.js
resources/assets/js/page/Post/PostForm/postDataList.js

feat: success overwrite otherStat
https://github.com/JiaAnTW/NCKU_Trans/pull/189
- /
- /post
- /admin/*
- component
- SideBar

feat: success overwrite otherStat

---

app/Http/Controllers/StudyController.php
resources/assets/js/_tests_/model/reducer/post/initStudy.js
resources/assets/js/components/StudyReader/StatisticBlock/StatisticItem/index.js
resources/assets/js/model/reducer/post/index.js
resources/assets/js/model/reducer/post/initStudy.js
resources/assets/js/model/reducer/post/mapToCustomFunction.js
resources/assets/js/page/Post/PostForm/postDataList.js
resources/assets/js/utils/redux/components/modal/transIntoModalData.js

- 在後端後端回傳其他統計資料並顯示於前端
- 在前端編輯其他統計資料
- /
- /post
- /admin/*
- component
- SideBar

fix: display otherStat data

---

app/Http/Controllers/StudyController.php

- Fix statistic of study post won't be updated in db when add or delete one in the request field.
- #187

fix: insert or delete statistic in study post can't update db

---

app/Http/Controllers/StudyController.php
resources/assets/js/components/atom/Label/index.js
resources/assets/js/components/atom/Label/style.js
resources/assets/js/components/atom/PairInput/index.js

- [support modify otherStat in backend](https://github.com/JiaAnTW/NCKU_Trans/commit/b284071eb335a19c327d29d9bd114109a3b66610)
- [feat: add delete button for otherStat in Post](https://github.com/JiaAnTW/NCKU_Trans/commit/3e13919ecaae536d7d3003bec04fecf7a12e6ef2)
- /
- /post
- /admin/*
- component
- SideBar

fix: update other stat in backend and add delete button

---

resources/assets/js/components/atom/Label/index.js
resources/assets/js/components/atom/Label/style.js
resources/assets/js/components/atom/PairInput/index.js
resources/assets/js/model/reducer/post/index.js

feat: deletable otherStat's input
* none
* none
- /
- /post
- /admin/*
- component
- SideBar

feat: deletable otherStat input

---

resources/assets/js/model/reducer/post/index.js

- fix: service crash cuz by api response order error
- none
- none
- /
- /post
- /admin/*
- component
- SideBar

fix: service crash cuz by api order error

---

app/Http/Controllers/StudyController.php
resources/assets/js/model/middleware/study.js
resources/assets/js/page/Study/Filter/ItemFilter/ItemFilterColumn/index.js
resources/assets/js/page/Study/Filter/ItemFilter/index.js
resources/assets/js/page/Study/Filter/index.js

- also fix some query error
#202 
- /admin/study

fix: call wrong API when admin filtering

---

app/Http/Controllers/StudyController.php

fix: correct misspelling on table name

---

resources/assets/js/components/Modal/ReaderModal/index.js
resources/assets/js/components/Modal/ReaderModal/usePageChange.js

fix: modal not close when pressing back button

---

resources/assets/js/components/Modal/ReaderModal/index.js
resources/assets/js/components/Modal/ReaderModal/usePageChange.js

修正開啟modal返回時無法關閉modal的問題
- https://github.com/JiaAnTW/NCKU_Trans/issues/198
- https://github.com/JiaAnTW/NCKU_Trans/pull/199
- /
- /post
- /admin/*
- component
- SideBar

fix: modal close

---

resources/assets/js/components/Modal/ReaderModal/usePageChange.js

Correct typo
- /
- /post
- /admin/*
- component
- SideBar

fix: correct typo
